# Generated by Django 5.2.7 on 2025-10-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0002_rename_gere_name_genre_genre_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='bio_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_tr',
            field=models.TextField(null=True),
        ),
    ]
