# Generated by Django 5.2.7 on 2025-10-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0003_actor_bio_en_actor_bio_ru_actor_bio_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name_en',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name_ru',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name_tr',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
