# Generated by Django 5.2.7 on 2025-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0004_alter_genre_genre_name_alter_genre_genre_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
    ]
