# Generated by Django 5.2.7 on 2025-10-16 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0005_alter_rating_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moview.rating'),
        ),
    ]
