# Generated by Django 5.2.7 on 2025-10-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0006_rating_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moview.rating'),
        ),
    ]
